### ISSUE TITLE
Calibration not possible

### ISSUE THREAD

**Issue by Invisible619** [ISO-B/pmb-pitft#12]
Hey,
the guide worked perfectly till the screen calibration. I was not able to calibrate it. 
This is what I get:
root@MusicBox:~# sudo TSLIB_FBDEVICE=/dev/fb1 TSLIB_TSDEVICE=/dev/input/touchscreen ts_calibrate
ts_open: No such file or directory

I skipped this step and followed the other steps, but the deamon won't start.
Could you please help me?

**Comment by ISO-B** [comment]
Try installing firmware with ```sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update 4815829b3f98e1b9c2648d9643dfe993054923ce``` that should do the job. I tought that I updated it to installing instructions last time, but apparently not.

**Comment by Invisible619** [comment]
Works fine now, thank you :)

Now I can't start the deamon.
`root@MusicBox:~# sudo python /root/pmb-pitft/pmb-pitft/ui.py start`
After that line the Pi ist working for a few seconds, the screen turns dark, it's not off, it's like after the second reboot.
```
root@MusicBox:~# sudo python /root/pmb-pitft/pmb-pitft/ui.py stop
pidfile /tmp/pmbpitft-daemon.pid does not exist. Daemon not running?
root@MusicBox:~#
```
Trying to stop the deamon causes this error.

**Comment by ISO-B** [comment]
Thats probably its not running. You could check pmb-pitft.log, it should tell what went wrong. Did you changed font config? if not and you are not using helvetica-neue-bold.ttf thats probably what is wrong. 

>From pitft-ui.py you need to change font if you are using something else than Helvetica Neue Bold and check that path is correct.
>
>To change font edit /root/pmb-pitft/pmb-pitft/pitft_ui.py file line 26 and replace "helvetica-neue-bold.ttf" with your own font name. example "OpenSans-Bold.ttf". You can download Open Sans from www.fontsquirrel.com/fonts/open-sans. Transfer ttf file to /root/pmb-pitft/pmb-pitft/ folder.

**Comment by Invisible619** [comment]
I didn`t changed the font config, in the readme it´s sounds like it is an optional step, I thought  helvetica-neue-bold is the standard font, now everything works perfect, thank you :)
I used WinSCP to transfer the OpenSans-Bold.ttf to the Pi, maybe it`s worth mention it.
If i have improvement ideas or questions in the next few days, I will let you know.
