### ISSUE TITLE
Download files

### ISSUE THREAD

**Issue by huberfe** [ISO-B/pmb-pitft#2]
In your instructions you write:

![image](https://cloud.githubusercontent.com/assets/6583519/5214798/135750a4-7621-11e4-97ca-4819044a22a0.png)

I think you make it easy for yourself. I'm struggeling with that step. I have no idea how to do this. Could you explain it a little further or show us a link?

Thank you, and thanks for your work.

**Comment by ISO-B** [comment]
Added @melvinow99 lines to read me.
