### ISSUE TITLE
Issue with network after 

### ISSUE THREAD

**Issue by ewigg** [ISO-B/pmb-pitft#5]
Im trying to set up my Adafruit PiTFT+touchscreen (http://www.adafruit.com/product/1601) with my Raspberry pi and Pi MusicBox 

I get a error after the firmware update. It keeps looping and produces an error saying drivers for network is missing. After command REPO_URI=https://github.com/notro/rpi-firmware rpi-update and a reboot it just loops the error. Both wifi and ethernet drivers is missing. It keeps repeating the error to infinity....

Dosent matter if I have wifi usb card in or just using ethernet. If I just using ethernet it produces an error for that to and keeps looping it.
![20150110_140316](https://cloud.githubusercontent.com/assets/6955113/5699996/16c2e39c-9a35-11e4-8245-9b8e75504e28.jpg)

**Comment by ISO-B** [comment]
I reinstalled Pi MusicBox 0.53 and I works atleast with usb wifi stick. Will test ethernet later.

**Comment by ewigg** [comment]
How did you do the reinstall? Is it necessary to hook it up to a keyboard? Or can I do It from the SD card?

**Comment by ISO-B** [comment]
Only way that I know is to write Pi MusicBox image to sd card again.

**Comment by ewigg** [comment]
Yea, that I know. Rewriting the SD card with Pi Musicbox again fixed the problem. But I want to find out hos to use my Adafruit PiTFT+touchscreen with it :) I have rewrite it many times, tried different cards and Raspberry pi's. 

But after rpi-update and reboot this happens.

**Comment by ISO-B** [comment]
I also ran those commands. After reboot ethernet and wifi works as usually. I am using RPI model B rev.1.

**Comment by ewigg** [comment]
I got this:

Model B Revision 1.0

Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter

**Comment by ewigg** [comment]
I resolved the issue with another wifi card. Bought this instead and now everything is working:

8178 Realtek Semiconductor Corp. RTL8192CU 802.11n WLAN Adapter

Thanks for the great guide! :)
