### ISSUE TITLE
pmb-pitft breaks PiMusicbox v0.5.2

### ISSUE THREAD

**Issue by mrWheel** [ISO-B/pmb-pitft#7]
Hi,
I've been trying to get this great script working with PiMusicbox but I keep getting problems.

At last I have the script working and the pitft screen works (with cover art and the lot....) but now mopidy stops working. 
<pre>ERROR    GStreamer error: state change failed and some element failed to post a proper error m
essage with the reason for the failure. Debug message: gstplaysink.c(1899): gen_audio_chain (): /GstPlayBin2:playbin20/G
stPlaySink:playsink0</pre> 
Tried to upgrade mopidy as in
<pre>Mopidy on Debian Pogolug: startup fails with UnicodeDecodeError [SOLVED]</pre>
That does work -sort off- but now the screen does not work anymore ..
<pre>$ sudo modprobe fbtft_device
FATAL: Module fbtft_device not found.</pre>
.. so I'm quite stuck after three day's full time trying ....
Does anyone has any ideas?

**Comment by ISO-B** [comment]
Just installed PiMusicBox 0.53 using instuctions on readme. Touchscreen works and it also plays music.

**Comment by mrWheel** [comment]
Sorry,
Rebuild everything with a new SD card and now I also have a working PiMusicBox with PiTFT screen.
There is eventhough still some strange behaviour if I kill (pmb) ui.py (running in the background) and then restart ui.py (also in the background). The message fbcon takes a very long time to apear and after that I get severall messages about killing the same previous kill.
Not sure if it is a currupted SD-card (again)... Will come back for this after I have investicated it further..
