### ISSUE TITLE
PITFT - Manual Calibration Error

### ISSUE THREAD

**Issue by herrsaidy** [ISO-B/pmb-pitft#9]
I have an problem when i want to calibrate the Touchscreen.
https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/touchscreen-install-and-calibrate#manual-calibration

I use " sudo TSLIB_FBDEVICE=/dev/fb1 TSLIB_TSDEVICE=/dev/input/touchscreen ts_calibrate" but I get this "ts_open: No such file or directory".  What is the Problem with that?

**Comment by ISO-B** [comment]
Did you created symlink for touchscreen?
https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/touchscreen-install-and-calibrate#setting-up-the-touchscreen

**Comment by herrsaidy** [comment]
Yes, I created the symlink. With the ISO from adafruit, everything works fine :(

**Comment by ISO-B** [comment]
Do you see touchscreen interface on /dev/input/ ?
```ls -la /dev/input/```

So your screen is working well, but touchscreen is not.

**Comment by ISO-B** [comment]
Which version of raspberry pi you are using?

Running rpi-update with ```sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update 4815829b3f98e1b9c2648d9643dfe993054923ce``` might solve problem. There is some new stuff going on on newest firmware, which causes touchscreen interface not to come up. Haven'd had time to look into it much yet.

**Comment by herrsaidy** [comment]
It works!!! Thank you! This was the Solution: sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update 4815829b3f98e1b9c2648d9643dfe993054923ce
